# Generated by Django 4.1.3 on 2022-12-09 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
