# Generated by Django 4.1.3 on 2022-12-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_merchantprofile_created_at_merchantprofile_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='dob',
            field=models.DateField(auto_now_add=True),
        ),
    ]
